### ISSUE TITLE
3 question dialogue template

### ISSUE THREAD

**Issue by antontimmermans** [scrubbless/MoM2ndTutorial#11]
Hi James,

I am not sure if you find this interresting enough to publish. I had to create a lot of dialogues with persons for my scenario so i made this 'template' for myself that can be Cut&paste into the event.ini file and the localization file:

Instructions to add a 3 question dialogue to a person token:

To make this run 3 variables need to be initalized at start of the scenario:
**PersonAskA,=,0 PersonAskB,=,0 PersonAskC,=,0**

Add the **EventPersonDialogue** to the person token in your scenario.

Copy this text can be into the event.ini file:
[DialogueEvent.ini.txt](https://github.com/scrubbless/MoM2ndTutorial/files/2776444/DialogueEvent.ini.txt)

Copy this into the Localization.English.txt file:
[Dialogue.Localization.English.txt](https://github.com/scrubbless/MoM2ndTutorial/files/2776445/Dialogue.Localization.English.txt)

Now what remains is for the scenario writer to become creative. Rename "Person" to what ever token you want to link it and start filling the dialogue with story text. Without editing it will look like this:
![image](https://user-images.githubusercontent.com/42072372/51437746-cd878080-1ca2-11e9-9857-d235bf594ecd.png)

**Comment by scrubbless** [comment]
Hi @antontimmermans, this is great thanks!

I have actually raised an issue about "modules" like this and support in Valkyrie.

I'll use your example here, as I have a coyple of pretty cool puzzles I intend to reuse in my scenarios and having the ability to share then (and for others to share theirs) would be awesome.

**Comment by antontimmermans** [comment]
addied this in a new chapter called: "Appendix; Code Snippets and Templates"
please close this issue if you think it is OK.

**Comment by scrubbless** [comment]
All good thanks!

Just a couple of formatting requests.

When you enter foot notes, etc. Can you put them in blue text with a bold Prefix. E.g.

**Important**: Your note

**Note**: Your note

This helps pick out the text to the reader.

Finally can you just add a note to your entries under the header:

Contributed by antontimmermans (and link your Github if you want).
This will give you some recognition and also help readers understand the shift in writing styles, being able to attribute it to a different person.
