### ISSUE TITLE
ability check description

### ISSUE THREAD

**Issue by antontimmermans** [scrubbless/MoM2ndTutorial#12]
As suggested in https://github.com/NPBruce/valkyrie/issues/1008 a short description of adding an ability check.
With special thanks to @scrubbless  and @redwolf2 for their example and wise words.

[abilitycheck[5237].docx](https://github.com/scrubbless/MoM2ndTutorial/files/2780146/abilitycheck.5237.docx)

**Comment by scrubbless** [comment]
Thanks @antontimmermans I see you've submitted a lot of suggestions. Would you be interested in collaborating with the tutorial doc? I could give you edit permissions

**Comment by antontimmermans** [comment]
I don't  not mind putting my text derectly into the document. That way you also get more time to work on your briliant scenarios :)
I will keep track of chages to the doc with issues in this repository so that you also get a trigger when i update somthing, If that is ok.

**Comment by scrubbless** [comment]
That would be perfect, thanks @antontimmermans, can you let me know your email address (or gmail if you have one) and i'll send you an invite.

**Comment by antontimmermans** [comment]
Added to chapter: "Advanced events" a section"Single Event with outcome based on test".
please close this issue if you think it is OK.

**Comment by scrubbless** [comment]
Thanks! Checked all good
