### ISSUE TITLE
Addition to translation section

### ISSUE THREAD

**Issue by antontimmermans** [scrubbless/MoM2ndTutorial#13]
@scrubbless, I see in the Valkyrie issues and Valkyrie channels more people wanting to translate. It maybe a good idea to extend the chapter on translations a little with the following:

To make future translation of you scenario more easy it will help you make a few default texts in your localization.<languague>.txt that you can later reference to. This way you only have to translate certain texts once and all related text will be translated in one go. Example:
```
ATTACK,Attack
CANCEL,Cancel
CONTINUE,Continue
EXPLORE,{action} Explore
INSPECT,{action} Inspect
NEVERMIND,"<i>""Nevermind""</i>"
OPEN,{action} Open
PICKUP,{action} Pick-up
SEARCH,{action} Search
```
In the example above, the text in capital letters is the reference text. And the text behind the comma (,) is what will be displayed in the game.
You can use these definitions in the rest of your text fileby using {qst:<reference>}. Example:

`EventTESTLightsOn.button1,{qst:CONTINUE}`

If you type the in button name in the Valkyrie editor (instead of Continue) {qst:CONTINUE} it will initially display your typed text. but when you leave the event and then go back to it you will see that Valkyrie automatically shows the button text in your chosen language.

You can combine these standard texts or add additional text to them for variation: Example:
Default text to be shown when inspecting the item:

`CONCLUSIVEFRSTA,Some nice text explaining what you see when you inspect the item.`

The first time you inspect this item you wish to show the text  and hand out one clue:

`EventQItemConclusiveEvdInspectFrstClueA.text,{qst:CONCLUSIVEFRSTA} You receive 1 Clue.`

Will show:
_Some nice text explaining what you see when you inspect the item. You receive 1 Clue._

The second time you inspect the same item, you only wish to repeat the information but NOT hand out a clue again;

`EventQItemConclusiveEvdShowFrstClueA.text,{qst:CONCLUSIVEFRSTA}`

Will show:
_Some nice text explaining what you see when you inspect the item._

**Comment by scrubbless** [comment]
Thank you @antontimmermans when I get a chance I'll add this to the tutorial. It's on my own list or something for me to start using and write up, but your explanation is perfect.

I'll put this directly in the tutorial if you are happy for me to.

**Comment by antontimmermans** [comment]
yes pls :)

**Comment by antontimmermans** [comment]
Added into chapter "Translating a scenario" a new section "Making your scenario ready for translation".
If you think its OK you can close this issue.

**Comment by scrubbless** [comment]
Thanks! Looks good
