### ISSUE TITLE
Organize your events

### ISSUE THREAD

**Issue by antontimmermans** [scrubbless/MoM2ndTutorial#15]
Added a chapter with the "organizing your events" with hints on naming and sorting events.

**Comment by antontimmermans** [comment]
Implemented, please close if you think it's OK

**Comment by scrubbless** [comment]
Oh Wow, you taught me something here! Thanks!

I've added credit to your events, this way people reading will understand why there is a difference in language used (we have different writing styles, both of which are perfectly fine).
