### ISSUE TITLE
Add an example for trigger vars

### ISSUE THREAD

**Issue by antontimmermans** [scrubbless/MoM2ndTutorial#16]
Add an example for using variables to triger an event.
see also https://github.com/NPBruce/valkyrie/issues/1001

**Comment by antontimmermans** [comment]
@scrubbless , added a description in chapter Variable types, a new sub-chapter called @ Variables, and a note in the chapter 'spawn the monster'. Kindly close the issue if you agree.

**Comment by scrubbless** [comment]
Every day is a school day, I learnt something new in this topic! Thanks Anton!
