### ISSUE TITLE
Hand-out Starting Clue(s)

### ISSUE THREAD

**Issue by antontimmermans** [scrubbless/MoM2ndTutorial#17]
@scrubbless As suggested in ticket https://github.com/NPBruce/valkyrie/issues/547 this tutorial describe how and when to hand-out Starting Clue tokens in a way that it more closely mimics the standard FFG Scenario flow.
The chapter Basic Start Event and Placing Tiles and Tokens could be a nice place for such description. Since it's originally your description, do you want to update it? (or shall I :))

**Comment by scrubbless** [comment]
Feel free to update it Anton :)

**Comment by antontimmermans** [comment]
Added a description in a new chapter called 'Start-up behavior of a scenario' as a sub-section of 'Tile Placement and Planning'
@scrubbless Kindly close if you agree with the content

**Comment by scrubbless** [comment]
Thanks Anton! Looks good
