### ISSUE TITLE
Explain usage of Audio and Music field.

### ISSUE THREAD

**Issue by antontimmermans** [scrubbless/MoM2ndTutorial#18]
add a bit more description of how to use the sound fields.
![image](https://user-images.githubusercontent.com/42072372/53443794-c0318480-3a0c-11e9-8c6d-788108886779.png)

Audio is inprinciple for sound effects and music of for longer playing effects/music/intro narration

audio: each new sound played before previous has finished is overlayed.
Music: each next new selected sound in the music field will stop the previous music and play the new one instead. Ideally used for introduction narration: to allow players to skip the long intro story.

**Comment by antontimmermans** [comment]
Solved in new chapter "Using built-in sound effects and music"
@scrubbless kindly close this ticket if you think it's OK.

**Comment by scrubbless** [comment]
I have corrected the grammar a little but, but looks good!
