### ISSUE TITLE
General Tips - Make the story as random as possible

### ISSUE THREAD

**Issue by NicolaZee** [scrubbless/MoM2ndTutorial#4]
>Make it as random as possible
>A problem with MoM 2e is that it doesn’t have a lot of replayability. The more randomised you make >your events, tokens (even tile placements) the more replayability people will get from your scenario.

I suggest modifying this because (for me) Mansions is first and foremost a story telling game.
There is an unavoidable  trade-off between randomness and narrative.  For example, games like Sherlock Holmes Consulting Detective have a strong narrative because there is no randomness.  With games like the Eldritch Horror board game, each game is different but the story is as much written by the players as the game because the narrative glue does not really exist to hold the random hodgepodge of events together.

So an important question to ask - before writing any scenario - is what kind of story the scenario is trying to tell?  Is it more like Escape from Innsmouth (where the narrative is fixed and unchanging) or more open-ended and random?  A one-off strong narrative story can be great if the story is great; even if it can only be played once.  A more open scenario with multiple possible paths and ways to victory can be even better as the scenario can be played multiple times - but is only better as long as the story makes sense.

The main thing to avoid is an incoherent random set of events combined with a random monster mash.  Random dungeon crawls work great for D&D but rarely work for horror.  

So my advice is (just as you recommend) make the story varied for replayability but only as long as this does not undermine the coherence of the story.

Just my opinion. : )

**Comment by NicolaZee** [comment]
While on the subject of putting story first, a general useful tip is not to get precious or hung up about any element of the story.  Every element of the story can (and probably will) get changed as long as the core of the story and the horror that arises from it are kept.

For example, let's imagine the Thing is your favourite movie and you're all fired up to create an epic Mansions scenario based on the film.  Well for a start there are no snowy wastes tiles or ice station rooms or for that matter a 'Thing' monster figure but change the monster to be a Thrall, change the setting to be an abandoned house in say the wilderness and it starts to looks more feasible.  The key question is what is the essential core of the movie?  Well, I think the horror comes not from the scariness of the creature in or of itself but relating to the stress of the characters desperately trying to determine who is infected.  Add a mechanism in the app for this and things start to look more interesting - and the randomness how arisen from the core of the story and the horror.

Just my opinion. : )

**Comment by scrubbless** [comment]
Thanks for the comments Nicola! I'll add your insights.

**Comment by scrubbless** [comment]
Hi Nicola, i've removed my randomness comment. I agree with you, the core of the story is more important.

I have also added your tip above to the guide, thanks again!

**Comment by NicolaZee** [comment]
Hello Scrubbles

 

And a thanks for your thanks! : )

 

Valkyrie has gone a bit quiet recently

How’s the development of your second scenario going?

I’m finding ‘difficult second album syndrome’ with mine.

It’s hard to come up with something entirely new and yet good.

 

All the best

Nicola
