### ISSUE TITLE
Adding variation

### ISSUE THREAD

**Issue by scrubbless** [scrubbless/MoM2ndTutorial#8]
Topic to explain adding optional variation, such as tiles, monsters and monsters.

**Comment by MilesTeg81** [comment]
just a couple of unsorted ideas and links that I came across while toying around with Valkyrie:

Custom Images/Audio
https://opengameart.org/ - awesome repository for CC0 graphics/sounds.

https://game-icons.net/ - free to use, customizable icons 

Advanced Topic: New Game Packages
https://github.com/NPBruce/valkyrie/issues/622
VERY useful if anyone wants to adapt valkyrie for other boardgames/custom campaigns or just wants to add custom tiles.

**Comment by scrubbless** [comment]
Awesome, thank you very much!
I've added the links to the Tools section.

I won't add a link to the Custom Tiles/Other Board games, just yet. As this is technically a guide to MoM to support official content.

However if I find a use case as I discover more from Valkyrie i'll write something up.

Thanks again 😁
