### ISSUE TITLE
Scenario tips&tricks

### ISSUE THREAD

**Issue by antontimmermans** [scrubbless/MoM2ndTutorial#9]
Hi Scrubbless,

As discussed on the forum I had some ideas to add to your tutorial. I am not sure if the information is useful, to much my style or if there are better ways if handling the things I describe.
I found the tricks I describe handy to make my scenario not too linear and allow free movement for investigators. It deals with complex/conditional placement of tiles and tokens while keeping the scenario's mechanics consistent.

The attached text is in rich text format. let me know a different format suits you better.

[Scenario tips&tricks.zip](https://github.com/scrubbless/MoM2ndTutorial/files/2586084/Scenario.tips.tricks.zip)

Best regards,
Anton

**Comment by scrubbless** [comment]
Thanks Anton!

Sorry for the late reply, I'll take a look and incorporate this into the guide within the next few days hopefully!

**Comment by scrubbless** [comment]
I have added your guide/tips to the document, you can find it on page 116:
https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit#heading=h.y9hjg1b298ye

Thank you again! 😁
